conda_config: "workflow/envs/conda.yaml"
ete3_conda_config: "workflow/envs/ete3_conda.yaml"

# ---- Pipeline configuration ---- (False to disable)
# ---- Alignment ----
dna_alignment: 'prank'       # 'prank' or 'mafft'
protein_alignment: 'mafft'   # 'prank' or 'mafft'
# ---- Filtration ----
dna_filtration: 'gblocks' # 'gblocks' or 'trimal'
protein_filtration: 'trimal' # 'gblocks' or 'trimal'
# ---- Рhylogenetic tree inference ---- (change to 'False' to disable)
iqtree_dna: True
iqtree_protein: True
mrbayes_dna: False
mrbayes_protein: False
astral: True # use iqtree for each dna alignment
phylip: True # use iqtree for each dna alignment
# ---- Рhylogenetic tree visualization ----
draw_phylotrees: True

# ---- Tool parameters ----
# ---- BUSCO ----
gene_prediction_tool: "metaeuk" # 'metaeuk' or 'augustus'
augustus_species: "human" # used only if 'gene_prediction_tool' == 'augustus'
busco_dataset_path: ""
busco_mode: "genome"
busco_params: ""
# ---- Alignment ----
prank_dna_params: "-codon"
mafft_dna_params: ""
prank_protein_params: ""
mafft_protein_params: "--anysymbol"
# ---- Filtration ----
gblocks_dna_params: "-t=Codons"
trimal_dna_params: "-automated1"
gblocks_protein_params: "-t=Protein"
trimal_protein_params: "-automated1"
# ---- Concatenation of alignments ----
alignment_file_prefix: "concat_alignment"
# ---- Рhylogenetic tree inference ----
# IQtree:
iqtree_dna_params: "-m TESTNEW -bb 1000" # -o homo_sapiens
iqtree_protein_params: "-m TESTNEW -bb 1000" # -o homo_sapiens
# Astral III:
iqtree_per_fna_params: "-m TESTNEW -bb 1000"
nodes_filtrataion_by_support: 70
astral_params: "--branch-annotate 2 --reps 1000"
# MrBayes:
mrbayes_dna_params: ""
mrbayes_protein_params: ""
mrbayes_block: "workflow/envs/mrbayes.block"
mrbayes_path: # path of MrBayes binary file
# PHYLIP
phylip_dnadist_params: "D\n" # use 'D\n' to set model to 'Kimura 2-parameter'. F84 model (default) if "".
phylip_neighbor_params: "" # use 'N\n' to set UPGMA. NJ (default) if "".
# ---- Рhylogenetic tree visualization ----
tree_visualization_params: "" # --outgroup

# ---- Directory structure ----
genome_dir: "genomes" # use an absolute path
output_dir: "results"
busco_dir: "busco"
species_ids_dir: "ids/species_ids"
common_ids_dir: "ids/"
merged_sequences_dir: "ids/merged_sequences"
alignments_dir: "alignments/raw/"
filtered_alignments_dir: "alignments/filtered/"
concat_alignments_dir: "concat_alignments"
iqtree_dir: "phylogeny/iqtree"
mrbayes_dir: "phylogeny/mrbayes"
astral_dir: "phylogeny/astral"
phylip_dir: "phylogeny/phylip"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"

# ---- Resources ----
# ---- Tool threads ----
busco_threads: 8
species_ids_threads: 1
common_ids_threads: 1
merged_sequences_threads: 1
mafft_threads: 1
prank_threads: 1
gblocks_threads: 1
trimal_threads: 1
iqtree_threads: 8
mrbayes_threads: 8
iqtree_per_fna_threads: 4
concat_newick_files_threads: 1
astral_threads: 4
phylip_threads: 1
visualization_threads: 1

# ---- Tool memory ----
busco_mem_mb: 10000
species_ids_mem_mb: 4000
common_ids_mem_mb: 4000
merged_sequences_mem_mb: 4000
mafft_mem_mb: 4000
prank_mem_mb: 6000
gblocks_mem_mb: 6000
trimal_mem_mb: 6000
iqtree_mem_mb: 10000
mrbayes_mem_mb: 10000
iqtree_per_fna_mem_mb: 10000
concat_newick_files_mem_mb: 2000
astral_mem_mb: 10000
phylip_mem_mb: 4000
visualization_mem_mb: 2000

# ---- Tool time ----
busco_time: "150:00:00"
species_ids_time: "01:00:00"
common_ids_time: "01:00:00"
merged_sequences_time: "01:00:00"
mafft_time: "10:00:00"
prank_time: "10:00:00"
gblocks_time: "10:00:00"
trimal_time: "10:00:00"
iqtree_time: "100:00:00"
mrbayes_time: "100:00:00"
iqtree_per_fna_time: "10:00:00"
concat_newick_files_time: "00:30:00"
astral_time: "5:00:00"
phylip_time: "5:00:00"
visualization_time: "00:30:00"


