# ---- Conda config ----
name: buscoclade
channels:
  - conda-forge
  - bioconda
dependencies:
  - busco=5.4.2
  - biopython
  - prank
  - mafft
  - gblocks
  - trimal
  - iqtree
  - astral-tree
  - newick_utils
#  - mrbayes